services:
  mongodb:
    container_name: splog-api-database
    image: mongo:8.0.17-noble
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-dbpassword}
    volumes:
      - splog_mongodb_data:/data/db
    networks:
      - splog-api-network

  app:
    build: .
    container_name: splog-api
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      PORT: ${PORT:-8080}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: ${MONGO_USER:-admin}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-dbpassword}
      MONGO_DATABASE: ${MONGO_DATABASE:-splog}
    depends_on:
      - mongodb
    networks:
      - splog-api-network

volumes:
  splog_mongodb_data:
    driver: local

networks:
  splog-api-network:
    name: splog-api-network
    driver: bridge